services:
  authservice:
    depends_on:
      - db
    build: ./auth-service
    ports:
      - "5000:5000"
    env_file:
      - ./auth-service/.env
    volumes:
      - ./auth-service:/app         # bind mount code for dev
      - ./shared-middleware:/app/shared-middleware  # bind mount the root middleware to each services /app/
      - /app/node_modules           # anonymous volume to protect container modules
    command: sh -c "npm install && npx prisma generate && npx prisma migrate deploy && npm run dev"


  userservice:
    depends_on:
      - db
    build: ./user-service
    ports:
      - "5001:5001"
    env_file:
      - ./user-service/.env
    volumes:
      - ./user-service:/app         # bind mount code for dev
      - ./shared-middleware:/app/shared-middleware
      - /app/node_modules           # anonymous volume to protect container modules
    command: sh -c "npm install && npx prisma generate && npx prisma migrate deploy && npm run dev"

  libraryservice:
    depends_on:
      - db
    build: ./library-service
    ports:
      - "5002:5002"
    env_file:
      - ./library-service/.env
    volumes:
      - ./library-service:/app         # bind mount code for dev
      - ./shared-middleware:/app/shared-middleware
      - /app/node_modules           # anonymous volume to protect container modules
    command: sh -c "npm install && npx prisma generate && npx prisma migrate deploy && npm run dev"

  db:
    image: postgres:16
    ports:
      - 5432:5432
    env_file:
      - .env.db
    volumes:
      - libraryData:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env.pg
    ports:
      - "8000:80"
    depends_on:
      - db

volumes:
  libraryData:



